// Database kota-kota populer untuk autocomplete
const citiesDatabase = [
    // Asia
    { name: "Tokyo", country: "Japan", countryCode: "JP" },
    { name: "Jakarta", country: "Indonesia", countryCode: "ID" },
    { name: "Delhi", country: "India", countryCode: "IN" },
    { name: "Shanghai", country: "China", countryCode: "CN" },
    { name: "Seoul", country: "South Korea", countryCode: "KR" },
    { name: "Singapore", country: "Singapore", countryCode: "SG" },
    { name: "Hong Kong", country: "Hong Kong", countryCode: "HK" },
    { name: "Bangkok", country: "Thailand", countryCode: "TH" },
    { name: "Kuala Lumpur", country: "Malaysia", countryCode: "MY" },
    { name: "Manila", country: "Philippines", countryCode: "PH" },
    { name: "Hanoi", country: "Vietnam", countryCode: "VN" },
    { name: "Taipei", country: "Taiwan", countryCode: "TW" },
    { name: "Beijing", country: "China", countryCode: "CN" },
    { name: "Osaka", country: "Japan", countryCode: "JP" },
    { name: "Mumbai", country: "India", countryCode: "IN" },
    { name: "Dhaka", country: "Bangladesh", countryCode: "BD" },
    { name: "Karachi", country: "Pakistan", countryCode: "PK" },
    { name: "Istanbul", country: "Turkey", countryCode: "TR" },
    
    // Europe
    { name: "London", country: "UK", countryCode: "GB" },
    { name: "Paris", country: "France", countryCode: "FR" },
    { name: "Berlin", country: "Germany", countryCode: "DE" },
    { name: "Madrid", country: "Spain", countryCode: "ES" },
    { name: "Rome", country: "Italy", countryCode: "IT" },
    { name: "Amsterdam", country: "Netherlands", countryCode: "NL" },
    { name: "Vienna", country: "Austria", countryCode: "AT" },
    { name: "Prague", country: "Czech Republic", countryCode: "CZ" },
    { name: "Warsaw", country: "Poland", countryCode: "PL" },
    { name: "Moscow", country: "Russia", countryCode: "RU" },
    { name: "Stockholm", country: "Sweden", countryCode: "SE" },
    { name: "Zurich", country: "Switzerland", countryCode: "CH" },
    { name: "Brussels", country: "Belgium", countryCode: "BE" },
    { name: "Lisbon", country: "Portugal", countryCode: "PT" },
    { name: "Athens", country: "Greece", countryCode: "GR" },
    { name: "Dublin", country: "Ireland", countryCode: "IE" },
    { name: "Copenhagen", country: "Denmark", countryCode: "DK" },
    { name: "Helsinki", country: "Finland", countryCode: "FI" },
    
    // North America
    { name: "New York", country: "USA", countryCode: "US" },
    { name: "Los Angeles", country: "USA", countryCode: "US" },
    { name: "Chicago", country: "USA", countryCode: "US" },
    { name: "Toronto", country: "Canada", countryCode: "CA" },
    { name: "Vancouver", country: "Canada", countryCode: "CA" },
    { name: "Mexico City", country: "Mexico", countryCode: "MX" },
    { name: "Miami", country: "USA", countryCode: "US" },
    { name: "San Francisco", country: "USA", countryCode: "US" },
    { name: "Washington DC", country: "USA", countryCode: "US" },
    { name: "Montreal", country: "Canada", countryCode: "CA" },
    { name: "Boston", country: "USA", countryCode: "US" },
    { name: "Seattle", country: "USA", countryCode: "US" },
    { name: "Houston", country: "USA", countryCode: "US" },
    { name: "Dallas", country: "USA", countryCode: "US" },
    { name: "Atlanta", country: "USA", countryCode: "US" },
    
    // South America
    { name: "São Paulo", country: "Brazil", countryCode: "BR" },
    { name: "Rio de Janeiro", country: "Brazil", countryCode: "BR" },
    { name: "Buenos Aires", country: "Argentina", countryCode: "AR" },
    { name: "Lima", country: "Peru", countryCode: "PE" },
    { name: "Bogotá", country: "Colombia", countryCode: "CO" },
    { name: "Santiago", country: "Chile", countryCode: "CL" },
    { name: "Caracas", country: "Venezuela", countryCode: "VE" },
    { name: "Quito", country: "Ecuador", countryCode: "EC" },
    { name: "Montevideo", country: "Uruguay", countryCode: "UY" },
    
    // Africa
    { name: "Cairo", country: "Egypt", countryCode: "EG" },
    { name: "Cape Town", country: "South Africa", countryCode: "ZA" },
    { name: "Johannesburg", country: "South Africa", countryCode: "ZA" },
    { name: "Nairobi", country: "Kenya", countryCode: "KE" },
    { name: "Casablanca", country: "Morocco", countryCode: "MA" },
    { name: "Lagos", country: "Nigeria", countryCode: "NG" },
    { name: "Accra", country: "Ghana", countryCode: "GH" },
    { name: "Addis Ababa", country: "Ethiopia", countryCode: "ET" },
    { name: "Dar es Salaam", country: "Tanzania", countryCode: "TZ" },
    
    // Oceania
    { name: "Sydney", country: "Australia", countryCode: "AU" },
    { name: "Melbourne", country: "Australia", countryCode: "AU" },
    { name: "Brisbane", country: "Australia", countryCode: "AU" },
    { name: "Perth", country: "Australia", countryCode: "AU" },
    { name: "Auckland", country: "New Zealand", countryCode: "NZ" },
    { name: "Wellington", country: "New Zealand", countryCode: "NZ" },
    { name: "Christchurch", country: "New Zealand", countryCode: "NZ" },
    
    // Middle East
    { name: "Dubai", country: "UAE", countryCode: "AE" },
    { name: "Abu Dhabi", country: "UAE", countryCode: "AE" },
    { name: "Riyadh", country: "Saudi Arabia", countryCode: "SA" },
    { name: "Doha", country: "Qatar", countryCode: "QA" },
    { name: "Kuwait City", country: "Kuwait", countryCode: "KW" },
    { name: "Muscat", country: "Oman", countryCode: "OM" },
    { name: "Tel Aviv", country: "Israel", countryCode: "IL" },
    { name: "Jerusalem", country: "Israel", countryCode: "IL" },
    { name: "Amman", country: "Jordan", countryCode: "JO" },
    { name: "Beirut", country: "Lebanon", countryCode: "LB" }
];